########################################
# 由于 GitHub API 限制，最多可以设置 60 个
########################################

links:
  ######## Stellar ########
  # XIVLauncher
  - https://api.github.com/repos/AtmoOmen/FFXIVQuickLauncher/releases?per_page=10
  # Dalamud
  - https://api.github.com/repos/AtmoOmen/Dalamud/releases/latest
