########################################
# 由于 GitHub API 限制，最多可以设置 60 个
########################################

links:
  # Stellar 最近更新
  - https://api.github.com/repos/xaoxuu/hexo-theme-stellar/releases?per_page=1
  # 近期动态
  - https://api.github.com/repos/xaoxuu/blog-timeline/issues
