name: Generator

on:
  watch:
    types: [started]
  schedule:
    - cron: '0/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run Generator
      run: |
        python generator/v1.py
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > generator/time.log
    - name: Commit
      run: |
        git config --global user.email github-actions@noreply.github.com
        git config --global user.name github-actions
        git add .
        git commit -m "Generate Json" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
